# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            'GAP Days Fall 2023'
tagline:          'A workshop for GAP developers and users'
description:      '16<sup>st</sup> to 20<sup>th</sup> October 2023'
location:         'University of Kaiserslautern-Landau'
url:              https://www.gapdays.de
baseurl:          /gapdays2023-fall
email:            mhorn@rptu.de #gapdays2023-fall@gapdays.de

exclude: 
    - "LICENSE.hyde.md"
    - "README.hyde.md"
    - "program.aux"
    - "program.log"
    - "program.out"
    - "program.tex"
    - "misc"
